/**
 * Invite Accept Page Component - Matches login page theme
 *
 * Allows new users to create an account using an invite link.
 * Uses the same dark warehouse theme as the login page.
 */

import React, { useState, useEffect } from 'react';
import {
  UserPlus,
  Loader2,
  AlertCircle,
  Check,
  Eye,
  EyeOff,
  Shield,
  Crown,
  User,
  Lock,
  Box,
  Package,
  Boxes,
} from 'lucide-react';
import {
  validateInviteToken,
  acceptInvite,
  type InviteToken,
  type CloudUser,
} from '../services/supabase/authService';

interface InviteAcceptPageProps {
  token: string;
  onSuccess: (user: CloudUser) => void;
  onCancel: () => void;
  theme: string; // Kept for compatibility, but we always use dark theme
}

export default function InviteAcceptPage({
  token,
  onSuccess,
  onCancel,
  theme,
}: InviteAcceptPageProps) {
  const [inviteToken, setInviteToken] = useState<InviteToken | null>(null);
  const [isValidating, setIsValidating] = useState(true);
  const [validationError, setValidationError] = useState<string | null>(null);

  const [displayName, setDisplayName] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [focusedField, setFocusedField] = useState<string | null>(null);

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  // Success state - show generated user code before redirecting
  const [isSuccess, setIsSuccess] = useState(false);
  const [generatedUserCode, setGeneratedUserCode] = useState<string | null>(null);

  // Validate token on mount
  useEffect(() => {
    validateToken();
  }, [token]);

  const validateToken = async () => {
    setIsValidating(true);
    setValidationError(null);

    try {
      const validatedToken = await validateInviteToken(token);
      setInviteToken(validatedToken);
    } catch (err) {
      setValidationError(err instanceof Error ? err.message : 'Invalid invite link');
    } finally {
      setIsValidating(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    // Validate inputs
    if (!displayName.trim()) {
      setSubmitError('Display name is required');
      return;
    }

    if (password.length < 4) {
      setSubmitError('Password must be at least 4 characters');
      return;
    }

    if (password !== confirmPassword) {
      setSubmitError('Passwords do not match');
      return;
    }

    setIsSubmitting(true);

    try {
      // User code is auto-generated by the server
      const result = await acceptInvite(token, displayName, password);
      setGeneratedUserCode(result.userCode);
      setIsSuccess(true);

      // Show success message for 3 seconds before redirecting
      setTimeout(() => {
        onSuccess(result.user);
      }, 3000);
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : 'Failed to create account');
      setIsSubmitting(false);
    }
  };

  // Loading state - matches login page
  if (isValidating) {
    return (
      <div className="min-h-screen bg-[#0f172a] flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="h-12 w-12 animate-spin mx-auto mb-4 text-indigo-400" />
          <p className="text-sm text-slate-400">Validating invite link...</p>
        </div>
      </div>
    );
  }

  // Invalid token state - matches login page
  if (validationError || !inviteToken) {
    return (
      <div className="min-h-screen bg-[#0f172a] flex items-center justify-center p-8">
        <div className="w-full max-w-md p-8 bg-slate-900 border border-slate-800 rounded-xl">
          <div className="text-center">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-red-500/10 mb-4">
              <AlertCircle className="h-8 w-8 text-red-400" />
            </div>
            <h2 className="text-xl font-bold mb-2 text-white">Invalid Invite Link</h2>
            <p className="text-sm mb-6 text-slate-400">
              {validationError || 'This invite link is not valid. Please contact your Team Leader for a new invite.'}
            </p>
            <button
              onClick={onCancel}
              className="w-full py-3.5 bg-slate-800 hover:bg-slate-700 text-white font-semibold rounded-lg transition-colors"
            >
              Return to Login
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Success message - matches login page
  if (isSuccess && generatedUserCode) {
    return (
      <div className="min-h-screen bg-[#0f172a] flex items-center justify-center p-8">
        <div className="w-full max-w-md p-8 bg-slate-900 border border-slate-800 rounded-xl">
          <div className="text-center">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-emerald-500/10 mb-4">
              <Check className="w-8 h-8 text-emerald-400" />
            </div>
            <h2 className="text-2xl font-bold mb-2 text-white">Account Created!</h2>
            <p className="text-sm mb-6 text-slate-400">
              Your account has been successfully created.
            </p>

            {/* Generated User Code */}
            <div className="p-6 bg-indigo-500/10 border border-indigo-500/20 rounded-xl mb-6">
              <p className="text-xs font-medium mb-2 text-indigo-400">Your User Code</p>
              <p className="text-3xl font-mono font-bold text-white">
                {generatedUserCode}
              </p>
              <p className="text-xs mt-2 text-slate-400">
                Save this code - you'll use it to log in
              </p>
            </div>

            {/* Loading redirect */}
            <div className="flex items-center justify-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin text-indigo-400" />
              <p className="text-sm text-slate-400">Redirecting to dashboard...</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Signup form - matches login page split layout
  return (
    <div className="min-h-screen bg-[#0f172a] flex overflow-hidden">
      {/* Left Side - Decorative (similar to login page) */}
      <div className="hidden lg:flex lg:w-1/2 relative bg-gradient-to-br from-indigo-500/10 via-[#0f172a] to-[#0f172a] p-12 flex-col justify-between">
        {/* Floating decorations */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-20 left-20 opacity-[0.03]">
            <Boxes className="w-96 h-96 text-indigo-500" strokeWidth={0.5} />
          </div>
          <Package className="absolute top-1/4 right-1/4 w-8 h-8 text-indigo-500/20 rotate-12" />
          <Box className="absolute top-1/3 left-1/3 w-6 h-6 text-indigo-500/15 -rotate-6" />
          <Shield className="absolute bottom-1/4 right-1/3 w-10 h-10 text-emerald-500/10 rotate-45" />
          <Crown className="absolute bottom-1/3 left-1/4 w-8 h-8 text-amber-500/15 rotate-12" />
        </div>

        {/* Content */}
        <div className="relative z-10">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-lg bg-indigo-600 flex items-center justify-center">
              <UserPlus className="w-5 h-5 text-white" />
            </div>
            <span className="text-indigo-400 font-mono text-sm tracking-wider">TEAM INVITATION</span>
          </div>
        </div>

        <div className="relative z-10 max-w-md">
          <h1 className="text-5xl font-bold text-white mb-6 leading-tight">
            Join the<br />
            <span className="text-indigo-400">Team</span>
          </h1>
          <p className="text-slate-400 text-lg leading-relaxed mb-8">
            You've been invited to join <strong className="text-white">{inviteToken.shiftName}</strong> as a <strong className="text-white">{inviteToken.role}</strong>.
          </p>

          {/* Invite details */}
          <div className="space-y-3">
            <div className="flex items-center gap-3 text-slate-400">
              <div className="w-2 h-2 rounded-full bg-indigo-400"></div>
              <span className="text-sm">Auto-generated secure user code</span>
            </div>
            <div className="flex items-center gap-3 text-slate-400">
              <div className="w-2 h-2 rounded-full bg-indigo-400"></div>
              <span className="text-sm">Invited by {inviteToken.createdByName}</span>
            </div>
            <div className="flex items-center gap-3 text-slate-400">
              <div className="w-2 h-2 rounded-full bg-indigo-400"></div>
              <span className="text-sm">Role: {inviteToken.role}</span>
            </div>
          </div>
        </div>

        <div className="relative z-10 text-slate-600 text-xs">
          "One team, one schedule"
        </div>
      </div>

      {/* Right Side - Signup Form */}
      <div className="flex-1 flex items-center justify-center p-8 lg:p-12">
        <div className="w-full max-w-sm">
          {/* Mobile header */}
          <div className="lg:hidden text-center mb-10">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full mb-4 bg-indigo-500/10">
              {inviteToken.role === 'Team Leader' ? (
                <Crown className="w-8 h-8 text-amber-400" />
              ) : (
                <Shield className="w-8 h-8 text-emerald-400" />
              )}
            </div>
            <h1 className="text-2xl font-bold text-white">Join {inviteToken.shiftName}</h1>
            <p className="text-slate-400 text-sm mt-1">{inviteToken.role} Role</p>
          </div>

          {/* Form header */}
          <div className="mb-8">
            <h2 className="text-2xl font-bold text-white mb-2">Create your account</h2>
            <p className="text-slate-400">Set up your credentials to get started</p>
          </div>

        <form onSubmit={handleSubmit} className="space-y-5">
          {/* Display Name */}
          <div>
            <label className="block text-sm font-medium text-slate-400 mb-2">
              Display Name
            </label>
            <div className="relative">
              <div className={`absolute left-0 top-0 bottom-0 w-12 flex items-center justify-center border-r transition-colors ${
                focusedField === 'displayName'
                  ? 'border-indigo-500/30 bg-indigo-500/5'
                  : 'border-slate-700 bg-slate-800/50'
              } rounded-l-lg`}>
                <User className={`w-4 h-4 transition-colors ${
                  focusedField === 'displayName' ? 'text-indigo-400' : 'text-slate-500'
                }`} />
              </div>
              <input
                type="text"
                value={displayName}
                onChange={(e) => {
                  setDisplayName(e.target.value);
                  setSubmitError(null);
                }}
                onFocus={() => setFocusedField('displayName')}
                onBlur={() => setFocusedField(null)}
                placeholder="John Doe"
                maxLength={50}
                autoFocus
                className={`w-full pl-14 pr-4 py-3.5 bg-slate-900 border rounded-lg text-white placeholder-slate-600 focus:outline-none transition-all ${
                  focusedField === 'displayName'
                    ? 'border-indigo-500/50 ring-1 ring-indigo-500/20'
                    : 'border-slate-800 hover:border-slate-700'
                }`}
              />
            </div>
          </div>

          {/* Password */}
          <div>
            <label className="block text-sm font-medium text-slate-400 mb-2">
              Password
            </label>
            <div className="relative">
              <div className={`absolute left-0 top-0 bottom-0 w-12 flex items-center justify-center border-r transition-colors ${
                focusedField === 'password'
                  ? 'border-indigo-500/30 bg-indigo-500/5'
                  : 'border-slate-700 bg-slate-800/50'
              } rounded-l-lg`}>
                <Lock className={`w-4 h-4 transition-colors ${
                  focusedField === 'password' ? 'text-indigo-400' : 'text-slate-500'
                }`} />
              </div>
              <input
                type={showPassword ? 'text' : 'password'}
                value={password}
                onChange={(e) => {
                  setPassword(e.target.value);
                  setSubmitError(null);
                }}
                onFocus={() => setFocusedField('password')}
                onBlur={() => setFocusedField(null)}
                placeholder="••••••••"
                className={`w-full pl-14 pr-12 py-3.5 bg-slate-900 border rounded-lg text-white placeholder-slate-600 focus:outline-none transition-all ${
                  focusedField === 'password'
                    ? 'border-indigo-500/50 ring-1 ring-indigo-500/20'
                    : 'border-slate-800 hover:border-slate-700'
                }`}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                tabIndex={-1}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300 transition-colors p-1"
              >
                {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
            <p className="text-xs mt-1 text-slate-500">
              Minimum 4 characters
            </p>
          </div>

          {/* Confirm Password */}
          <div>
            <label className="block text-sm font-medium text-slate-400 mb-2">
              Confirm Password
            </label>
            <div className="relative">
              <div className={`absolute left-0 top-0 bottom-0 w-12 flex items-center justify-center border-r transition-colors ${
                focusedField === 'confirmPassword'
                  ? 'border-indigo-500/30 bg-indigo-500/5'
                  : 'border-slate-700 bg-slate-800/50'
              } rounded-l-lg`}>
                <Lock className={`w-4 h-4 transition-colors ${
                  focusedField === 'confirmPassword' ? 'text-indigo-400' : 'text-slate-500'
                }`} />
              </div>
              <input
                type={showPassword ? 'text' : 'password'}
                value={confirmPassword}
                onChange={(e) => {
                  setConfirmPassword(e.target.value);
                  setSubmitError(null);
                }}
                onFocus={() => setFocusedField('confirmPassword')}
                onBlur={() => setFocusedField(null)}
                placeholder="••••••••"
                className={`w-full pl-14 pr-4 py-3.5 bg-slate-900 border rounded-lg text-white placeholder-slate-600 focus:outline-none transition-all ${
                  focusedField === 'confirmPassword'
                    ? 'border-indigo-500/50 ring-1 ring-indigo-500/20'
                    : 'border-slate-800 hover:border-slate-700'
                }`}
              />
            </div>
          </div>

          {/* Error Message */}
          {submitError && (
            <div className="flex items-center gap-3 p-3 bg-red-500/10 border border-red-500/20 rounded-lg">
              <AlertCircle className="w-4 h-4 text-red-400 flex-shrink-0" />
              <p className="text-sm text-red-400">{submitError}</p>
            </div>
          )}

          {/* Submit Button */}
          <button
            type="submit"
            disabled={isSubmitting || !displayName || !password || !confirmPassword}
            className="w-full flex items-center justify-center gap-2 py-3.5 bg-indigo-600 hover:bg-indigo-500 disabled:bg-indigo-600/50 disabled:cursor-not-allowed text-white font-semibold rounded-lg transition-all group"
          >
            {isSubmitting ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                <span>Creating account...</span>
              </>
            ) : (
              <>
                <UserPlus className="w-5 h-5" />
                <span>Create Account</span>
              </>
            )}
          </button>
        </form>

          {/* Footer */}
          <div className="mt-10 pt-6 border-t border-slate-800">
            <button
              type="button"
              onClick={onCancel}
              className="w-full text-sm text-slate-500 hover:text-indigo-400 transition-colors"
            >
              Return to login
            </button>
            <p className="text-center text-slate-600 text-xs mt-4">
              Secure invite-only registration
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
